### ISSUE TITLE
Broken parsing or pipeline for the same document.

### ISSUE THREAD

**Issue by fabiobatalha** [pkp/ots#113]
Doing tests with the API and User interface, I realized that OTS may could have some broken transformation pipelines.

The same files were submitted twice.

First through the API and them through the webiste.

The website seems to work better, but I didn't make a huge test to ensure this.

|mode|attempt|1043026ar.doc|1043123ar.docx|1043159ar.docx|
|---|---|---|---|---|
|API|first|2253 (Failed)| 2254 (Pending)| 2255 (Finished)|
|website|second|2257(Finished)|2256 (Finished)|2258(Finished)|
|API|third|2260 (Finished)|2261(Finished)|2264 (Finished)|
|API|fourth|2265 (Failed)|2266(Finished)|2267 (Finished)|

**Comment by axfelix** [comment]
The failure in this case was due to the LibreOffice service -- in rare cases the listener can get overloaded. We've tried to stagger requests internally to avoid this happening but there are obviously some cases where it can still happen. This behaviour shouldn't differ across the website and the API; just a coincidence.

**Comment by fabiobatalha** [comment]
Ok thanks.

I will work around these situations in our environment.
