### ISSUE TITLE
Mismatching reference ids

### ISSUE THREAD

**Issue by fabiobatalha** [pkp/ots#128]
Reference id in the body:

``` xml
        <p>D'un point de vue psychodynamique, en général, l’impulsivité est  plutôt abordée sous l’angle du passage à l'acte (<xref ref-type="bibr" id="IDd68b9f40-2713-4554-98ef-a4f5cd511d90">A. Raoult, 2006</xref>).  </p>
```

Reference id:

``` xml
      <ref id="R48">
        <element-citation publication-type="journal">
          <person-group person-group-type="author">
            <name>
              <surname>Raoult</surname>
              <given-names>PatrickAnge</given-names>
            </name>
          </person-group>
          <article-title>Clinique et psychopathologie du passage à l\textquotesingleacte</article-title>
          <source>Bulletin de psychologie</source>
          <year>2006</year>
        </element-citation>
      </ref>
```

This behaviour lead to references mismatching in Texture

![screenshot from 2018-03-02 13-40-04](https://user-images.githubusercontent.com/504142/36915595-4271a58e-1e1f-11e8-8e9a-1114cd0e41d6.png)

**Comment by axfelix** [comment]
Thanks! We've done a lot of work on this part over the past few years and it should be a very rare issue when it does occur.

In this case, it looks like it's not a mismatch (which would be more concerning, since we shouldn't ever be seeing false positives here) but just a failed match (the xref element would have a `rid` if it actually matched; the `id` is more of a pkey for the xref than a link to the references themselves), which is an acceptable failure.
